function [RX] = channel(RX, SPS, k, EbN0)

channel = comm.AWGNChannel(...
    'NoiseMethod', 'Signal to noise ratio (Eb/No)', ...
    'EbNo', EbN0, ...
    'BitsPerSymbol', k, ...
    'SamplesPerSymbol', SPS, ...
    'SignalPower', 1/SPS);

RX = channel(RX);

end